### ISSUE TITLE
What is the proper way to update tool progress?

### ISSUE THREAD

**Issue by pillowfication** [alteryx/ayx-developer-sdk#30]
My tool has a single output, and I'd like to be able to somehow update the progress of the tool as it does work in `on_complete`.

I've tried the following without success:
```python
def on_complete(self) -> None:
    self.provider.io.update_progress(0)
    for n in range(count):
        self.do_work()
        self.provider.io.update_progress((n + 1) / count * 100)
    batch = self.create_batch()
    self.provider.write_to_anchor("Output", batch)
```

**Comment by pillowfication** [comment]
Never mind. Seems to simply be unavailable.

```python
def update_progress(self, percent: float) -> None:  # noqa: D102
    # Not currently implemented in any version
    pass
```

**Comment by ayx-david-ung** [comment]
Hello @pillowfication ,

Yes, this function is not available at the moment. We have a backlog item to enable this feature in the future. But at this time we have not prioritized enabling it in Platform v2 SDK.
