### ISSUE TITLE
How do I change the Help button URL?

### ISSUE THREAD

**Issue by pillowfication** [alteryx/ayx-developer-sdk#31]
All tools have this Help button in the side panel:
![image](https://github.com/alteryx/ayx-developer-sdk/assets/7277535/70c2c769-db65-42e1-9b68-b2ee7a80fc77)

Custom tools seem to point to [https://help.alteryx.com/developer-help](https://help.alteryx.com/developer-help) by default, but I would like for it to point to a help page of my own for this tool. I didn't see anything regarding it on the [Tool Configurations](https://alteryx.github.io/ayx-python-sdk/config_xml.html) documentation.

**Comment by ayx-david-ung** [comment]
Hello @pillowfication ,

We did not yet automate the steps to easily add Help URL to a custom tool. We do have an manaual solution.

You can modify that in the `{toolName}Config.xml` file. Before building the tool, modify the XML file in the `workspace\configuration\{ToolName}` folder. 

The line is:

`<GuiSettings Html="index.html" Icon="toolIcon.png" SDKVersion="10.1" Help="https://help.alteryx.com/current/designer/ToolNameHere">`


Or 

You should be able to edit the` "help_url" ` key in `ayx_workspace.json` (under `["tools"][<name of your tool>]["configuration"]["help_url"]`) and change the URL from there. This will automatically change it in the config.xml as well


Source: (Already answered in Community)
https://community.alteryx.com/t5/Alteryx-IO-Discussions/How-do-I-change-the-Help-button-URL-for-a-Custom-Tool/td-p/1180113

**Comment by pillowfication** [comment]
Seems the way to do it is through `tools.[plugin].configuration.help_url` in `ayx_workspace.json`. Editing the value in `{plugin}Config.xml` doesn't seems safe because it gets overwritten by the `ayx_workspace.json` value occasionally.
